return {
    pt_kill_object_process_by_file_path = "pt_kill_object_process_by_file_path",
    pt_kill_object_process_by_image = "pt_kill_object_process_by_image",
    pt_kill_object_process_by_name = "pt_kill_object_process_by_name",
    pt_kill_object_process_by_name_and_id = "pt_kill_object_process_by_name_and_id",
    pt_kill_object_process_by_image_and_id = "pt_kill_object_process_by_image_and_id",
    pt_kill_object_process_tree_by_file_path = "pt_kill_object_process_tree_by_file_path",
    pt_kill_object_process_tree_by_image = "pt_kill_object_process_tree_by_image",
    pt_kill_object_process_tree_by_name = "pt_kill_object_process_tree_by_name",
    pt_kill_object_process_tree_by_name_and_id = "pt_kill_object_process_tree_by_name_and_id",
    pt_kill_object_process_tree_by_image_and_id = "pt_kill_object_process_tree_by_image_and_id",
    pt_kill_subject_process_by_image = "pt_kill_subject_process_by_image",
    pt_kill_subject_process_by_name = "pt_kill_subject_process_by_name",
    pt_kill_subject_process_by_name_and_id = "pt_kill_subject_process_by_name_and_id",
    pt_kill_subject_process_by_image_and_id = "pt_kill_subject_process_by_image_and_id",
    pt_kill_subject_process_tree_by_image = "pt_kill_subject_process_tree_by_image",
    pt_kill_subject_process_tree_by_name = "pt_kill_subject_process_tree_by_name",
    pt_kill_subject_process_tree_by_name_and_id = "pt_kill_subject_process_tree_by_name_and_id",
    pt_kill_subject_process_tree_by_image_and_id = "pt_kill_subject_process_tree_by_image_and_id",
}
